### ISSUE TITLE
Move to the oxc project?

### ISSUE THREAD

**Issue by Boshen** [oxc-project/mirrors-oxlint#1]
It would be nice to move this to the oxc project https://github.com/oxc-project/

I'll update the documentation website once moved.

```
repos:
-   repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v0.0.19
    hooks:
    -   id: oxlint
        verbose: true
```

**Comment by haocheng6** [comment]
Sounds good to me.

It seems like cannot directly transfer the repository to the oxc-project organization, so I transferred to you and then you can transfer it to the oxc-project. I have not transferred repositories before, so I am not sure if that is the right thing to do. If there is anything else I need to do, feel free to let me know.

**Comment by Boshen** [comment]
Thank you! I'll update the website soon.
